// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int numberOfRuns = Integer.parseInt(args[0]);

		int bigNum = 0;
		int smallNum = 0;
		double randomNum = 0;
		double ratio;

		for (int i = 0; i < numberOfRuns; i++){
			randomNum = Math.random();
			if (randomNum > 0.5) bigNum++;
			else smallNum++;
		}
		System.out.println("> 0.5: " + bigNum + " times");
		System.out.println("<= 0.5: " + smallNum + " times");

		double newSmallNum = smallNum;
		double newBigNum = bigNum;

		if (bigNum > 0);{
			if (smallNum > 0) {
				if (smallNum > bigNum){
					 ratio = newBigNum / newSmallNum;
				} 
				else ratio = newSmallNum / newBigNum;
				System.out.println("ratio: " + ratio);
			}
		}
	}
}
